//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Backwater
    {
        public int ID_Fish { get; set; }
        public string Name { get; set; }
        public Nullable<int> Fish_Count { get; set; }
        public Nullable<System.DateTime> Date_Start { get; set; }
        public string Date_End { get; set; }
        public string Fish_Name { get; set; }
        public Nullable<int> Fish_Size { get; set; }
        public Nullable<int> FK_Employee { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Beholder_Employee Beholder_Employee { get; set; }
        public virtual Sales_Department Sales_Department { get; set; }
    }
}
