//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beholder_Employee
    {
        public int ID_Employee { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Backwater Backwater { get; set; }
    }
}
