//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemoTestEntities2 : DbContext
    {
        public DemoTestEntities2()
            : base("name=DemoTestEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<Backwater> Backwater { get; set; }
        public virtual DbSet<Beholder_Employee> Beholder_Employee { get; set; }
        public virtual DbSet<Sales_Department> Sales_Department { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
