//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Department
    {
        public int ID_Department { get; set; }
        public Nullable<int> Orders_Count { get; set; }
        public Nullable<int> Fishing_Count { get; set; }
        public Nullable<int> Average_Fishin_Time { get; set; }
    
        public virtual Backwater Backwater { get; set; }
    }
}
